version: '3.8'

services:
  app:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/performer
    depends_on:
      - postgres
    environment:
      RAILS_ENV: development

  postgres:
    image: postgres:14
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD

  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/performer
    depends_on:
      - postgres
    environment:
      RAILS_ENV: test
