version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/performer
    depends_on:
      - postgres
    environment:
      RAILS_ENV: development

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  postgres:
    image: postgres:14
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD

  test:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/performer
    depends_on:
      - postgres
    environment:
      RAILS_ENV: test

  vps:
    build:
      context: .
      dockerfile: Dockerfile.vps
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
      - '22:22'
