default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { '5432' } %>
  username: <%= ENV.fetch('DATABASE_USER_NAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: performer_development

test:
  <<: *default
  database: performer_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'performer_production' } %>
