default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { '5432' } %>

development:
  <<: *default
  database: performer_development

test:
  <<: *default
  database: performer_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'performer_production' } %>
  username: <%= ENV.fetch('DB_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>
